### ISSUE TITLE
Improve `Semigroup` instance

### ISSUE THREAD

**Issue by andreasabel** [andreasabel/ini#2]
@chris-martin has done unmerged work on the `Semigroup` instance, see
- https://github.com/chrisdone/ini/pull/32
- https://github.com/chrisdone/ini/issues/31

@chris-martin : Do you want to port your PR to this repo?  Do you want to co-maintain `ini`?

**Comment by andreasabel** [comment]
Ping @chris-martin.

**Comment by chris-martin** [comment]
Hi! Yes sorry I forgot all about this. Will resubmit the PR. I do still use the `ini` library and so I would be happy to help co-maintain.

**Comment by andreasabel** [comment]
@chris-martin Thanks for helping out with maintenance!
I invited you to this repo and added you on Hackage: https://hackage.haskell.org/package/ini/maintainers/

When you make releases, please stick to the current changelog format: https://github.com/andreasabel/ini/blob/092dd89d38fd9005241e33966ad1bd1db8709379/CHANGELOG.md?plain=1#L1-L8
By this I mean that the changelog entry should contain, besides more substantial information,
- date and name of maintainer who made the release
- links to the issues addressed (or links to PRs that do not have an issue)
- range of GHC versions supported by this release.

It is a bit unfortunate that the previous maintainer @chrisdone archived his repo instead of transferring it, so we do not have continuity in issue numbers.

This repo should be unforked at some point, but it could also be moved from my private account to a suitable organization.
